using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Generate_Character : MonoBehaviour
{
    // Start is called before the first frame update
    [SerializeField] private GameObject character; //model to be generated by this button
    [SerializeField] private Vector3 startPos; //starting position of model (in front of home base)

    [SerializeField] private Button button;
    void Start()
    {
        button = this.GetComponent<Button>();
    }

    // Update is called once per frame
    void Update()
    {

    }

    public void onClick()
    {
        Instantiate(character, startPos, Quaternion.identity);
    }
}
